bert:
  arch: large
  batch_size: 2
  num_iterations: 10000
  request_rate: 8
mobilenet_v2:
  arch: mobilenet_v2
  batch_size: 4
  num_iterations: 10000
  request_rate: 100
models:
  model0:
    mode: eval
    name: resnet50
  model1:
    mode: eval
    name: resnet50
policy: MPS
resnet101:
  arch: resnet101
  batch_size: 4
  num_iterations: 10000
  request_rate: 40
resnet50:
  arch: resnet50
  batch_size: 4
  num_iterations: 10000
  request_rate: 80
shared_config:
  distribution: trace
  pin_memory: true
  seed: 42
  trace_path: ../../inter_arrival_times.json
transformer:
  arch: base
  batch_size: 4
  num_iterations: 10000
  request_rate: 20
