---
policy: tick-tock # either "temporal" or "tick-tock"
model0:
  name: nasnet # should strictly correspond to the directory name
  optimizer: SGD
  batch_size: 32
model1:
  name: vision # should strictly correspond to the directory name
  arc: mobilenet_v2
  optimizer: SGD
  batch_size: 32



